/** Timeline redesign palette — pair with non-color cues for accessibility (G4). */
export const TimelineTokens = {
  billDueBg: '#E6F1FB',
  billDueFg: '#0C447C',
  billDueBorder: '#85B7EB',
  billPaidBg: '#EAF3DE',
  billPaidFg: '#3B6D11',
  billPaidBorder: '#97C459',
  todayRing: '#378ADD',
  dotDue: '#378ADD',
  dotPaid: '#639922',
  dotPending: '#BA7517',
  amountOwe: '#A32D2D',
  amountPaid: '#3B6D11',
  amountPending: '#854F0B',
  badgeBlueBg: '#E6F1FB',
  badgeGreenBg: '#EAF3DE',
  badgeAmberBg: '#FAEEDA',
  badgeRedBg: '#FCEBEB',
  captureCtaBg: '#E6F1FB',
  captureCtaBorder: '#85B7EB',
  captureCtaFg: '#0C447C',
  segmentActiveBg: '#E6F1FB',
  segmentBorder: '#E2E8F0',
  horizonBorder: '#CBD5E1',
  horizonBg: '#F8FAFC',
  purgeBorder: '#F4A4A4',
  purgeBg: '#FEF2F2',
  weekBadgeBg: 'rgba(15, 23, 42, 0.72)',
  weekBadgeFg: '#FFFFFF',
  backfillBannerBg: '#FAEEDA',
  backfillBannerFg: '#854F0B',
  historyBannerBg: '#F1F5F9',
  historyBannerFg: '#475569',
} as const;
